# Generated by Django 6.0.8 on 2026-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomycategory',
            name='full_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
