# Generated by Django 6.0.8 on 2026-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_extra_fields_and_detected_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_collection',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
